In [201]:
"""
================================================================================
                    PANDAS COMPLETE MASTERY HANDBOOK (Part - 01)
                         Introduction to Series & DataFrames
================================================================================

Pandas = Panel Data / Python Data Analysis Library

Why Pandas?
-----------
✔ The premier data manipulation and analysis tool built on top of NumPy.
✔ Introduces key structural objects: Series (1D) and DataFrames (2D tables).
✔ Seamlessly handles heterogeneous data types across columns.
✔ Built-in label-based indexing, alignment, dropping, and boolean slicing.
"""

import numpy as np
import pandas as pd

In [231]:
# ==============================================================================
# 1. PANDAS SERIES: INITIALIZATION AND CUSTOM INDEXING
# ==============================================================================

print("--- Pandas Series Fundamentals ---")

"""
A Series is a one-dimensional labeled array capable of holding any data type. 
It consists of an axis labels array (called index) and the actual data values.
"""
# 1A. Initializing a Series from a Raw NumPy Array (Default Numeric Indexing)
numpy_raw_data = np.array([2, 4, 1, 6])
default_series = pd.Series(numpy_raw_data)

print("\nDefault Indexed Series:")
default_series

--- Pandas Series Fundamentals ---

Default Indexed Series:

0    2
1    4
2    1
3    6
dtype: int64

In [203]:
# 1B. Initializing a Series with Custom Explicit String Indices
custom_string_indices = np.array(['a', 'b', 'c', 'd'])
labeled_series = pd.Series(numpy_raw_data, index=custom_string_indices)

print("Custom Labeled Series:")
labeled_series

Custom Labeled Series:

a    2
b    4
c    1
d    6
dtype: int64

In [204]:
# 1C. Initializing a Series Direct from a Standard Python Dictionary
dictionary_source = {'a': 11, 'b': 12, 'c': 13}
dictionary_series = pd.Series(dictionary_source)

print("Series Built from Dictionary:")
dictionary_series

Series Built from Dictionary:

a    11
b    12
c    13
dtype: int64

In [206]:
# ==============================================================================
# 2. DATAFRAME CREATION MECHANICS: CONSTRUCTORS
# ==============================================================================

print("--- DataFrame Construction Blueprints ---")
"""
A DataFrame is a two-dimensional tabular data structure with rows and columns. 
Think of it like an optimized, programmatic SQL table or Excel spreadsheet.
"""

# 2A. Method 1: Creating a DataFrame from a Dictionary of Aligned Lists
student_dictionary_table = {
    "Name": ["Adar", "Jahid", "Dipto"],
    "ID": [39, 25, 34],
    "CGPA": [3.30, 4.00, 3.70]
}
df_from_dict = pd.DataFrame(student_dictionary_table)

print("\nDataFrame From Dictionary Structure:")
df_from_dict

--- DataFrame Construction Blueprints ---

DataFrame From Dictionary Structure:

    Name  ID  CGPA
0   Adar  39   3.3
1  Jahid  25   4.0
2  Dipto  34   3.7

In [207]:
# 2B1. Method 2: Creating a DataFrame from a Nested List
student_nested_list = [
    ["Adar", 39, 3.30],
    ["Jahid", 25, 4.00],
    ["Dipto", 34, 3.70]
] 
df_student_profile_without_header = pd.DataFrame(student_nested_list)

print("DataFrame From Nested List:")
df_student_profile_without_header

DataFrame From Nested List:

       0   1    2
0   Adar  39  3.3
1  Jahid  25  4.0
2  Dipto  34  3.7

In [209]:
# 2B2. Method 2: Creating a DataFrame from a Nested List with Explicit Column Headers
column_headers = ["Name", "ID", "CGPA"]
df_student_profile_with_header = pd.DataFrame(student_nested_list, columns=column_headers)

print("DataFrame From Nested List & Custom Column Headings:")
df_student_profile_with_header

DataFrame From Nested List & Custom Column Headings:

    Name  ID  CGPA
0   Adar  39   3.3
1  Jahid  25   4.0
2  Dipto  34   3.7

In [210]:
# ==============================================================================
# 3. COLUMN EXTRACTION, SELECTION, AND MUTATION PIPELINES
# ==============================================================================
print("--- Column Manipulations and Axis Dropping ---")

# 3A. Extracting a Sub-DataFrame via Single-Column and Multi-Column Selection List
single_column_selection = df_student_profile_with_header["Name"]

print("\nIsolated Target Columns Selection:")
single_column_selection

--- Column Manipulations and Axis Dropping ---

Isolated Target Columns Selection:

0     Adar
1    Jahid
2    Dipto
Name: Name, dtype: object

In [211]:
multi_column_selection = df_student_profile_with_header[["Name", "CGPA"]]

print("Isolated Target Columns Selection:")
multi_column_selection

Isolated Target Columns Selection:

    Name  CGPA
0   Adar   3.3
1  Jahid   4.0
2  Dipto   3.7

In [58]:
# 3B. Dynamically Appending/Mutating a New Column Feature
df_student_profile_with_header["Age"] = [23, 24, 22]

print("DataFrame After Column Feature Inflation:")
df_student_profile_with_header

DataFrame After Column Feature Inflation:

    Name  ID  CGPA  Age
0   Adar  39   3.3   23
1  Jahid  25   4.0   24
2  Dipto  34   3.7   22

In [60]:
# 3C. Dropping Features: Temporary Copy vs. Inplace Permanent Overwrites
# Using axis=1 explicitly flags target targets as COLUMNS. 
# Using axis=0 explicitly flags targets as ROWS.

# 3C1. Non-destructive drop (Returns a modified copy, parent layout is unchanged)
df_temporary_drop = df_student_profile_with_header.drop('Age', axis=1)

print("Returned Copy DataFrame (Age Column Dropped):")
df_temporary_drop

Returned Copy DataFrame (Age Column Dropped):

    Name  ID  CGPA
0   Adar  39   3.3
1  Jahid  25   4.0
2  Dipto  34   3.7

In [61]:
print("Parent Target DataFrame (Still Retains Age Column):")
df_student_profile_with_header

Parent Target DataFrame (Still Retains Age Column):

    Name  ID  CGPA  Age
0   Adar  39   3.3   23
1  Jahid  25   4.0   24
2  Dipto  34   3.7   22

In [62]:
# 3C2. Destructive drop (Modifies the memory footprint permanently using inplace=True)
df_student_profile_with_header.drop('Age', axis=1, inplace=True)

print("Parent DataFrame After Inplace Dropping (Age Extinguished Permanently):")
df_student_profile_with_header

Parent DataFrame After Inplace Dropping (Age Extinguished Permanently):

    Name  ID  CGPA
0   Adar  39   3.3
1  Jahid  25   4.0
2  Dipto  34   3.7

In [63]:
# 3C3. Batch Dropping Multiple Columns Simultaneous
df_multi_dropped = df_student_profile_with_header.drop(['ID', 'CGPA'], axis=1)

print("Batch Column Drop Execution Output:")
df_multi_dropped

Batch Column Drop Execution Output:

    Name
0   Adar
1  Jahid
2  Dipto

In [64]:
# 3C4. Row Elimination via Axis Zero
df_row_dropped = df_student_profile_with_header.drop(0, axis=0)

print("Row Index [0] Dropped Output:")
df_row_dropped

Row Index [0] Dropped Output:

    Name  ID  CGPA
1  Jahid  25   4.0
2  Dipto  34   3.7

In [215]:
# ==============================================================================
# 4. LOCATION INDEXING METRICS (.loc vs .iloc)
# ==============================================================================
print("--- Advanced Row Retrieval Operations via loc and iloc ---")

"""
- .loc: Label-Based index selection. Accesses data points using literal named indices/labels.
- .iloc: Integer-Position Based selection. Accesses data points via zero-indexed integer slots.
"""

# 4A. Label Slicing Row extractions
print("\nSingle Row Extraction Label-Based (.loc[0]):")
df_student_profile_with_header.loc[0]

--- Advanced Row Retrieval Operations via loc and iloc ---

Single Row Extraction Label-Based (.loc[0]):

Name    Adar
ID        39
CGPA     3.3
Name: 0, dtype: object

In [212]:
print("Batch Multi-Row Label Selection List (.loc[[0, 1]]):")
df_student_profile_with_header.loc[[0, 1]] # Grabs rows matching index labels 0 and 1

Batch Multi-Row Label Selection List (.loc[[0, 1]]):

    Name  ID  CGPA
0   Adar  39   3.3
1  Jahid  25   4.0

In [216]:
# 4B. Absolute Positional Integer Indexing Row extraction
print("Absolute Integer Position Extraction (.iloc[2]):")
df_student_profile_with_header.iloc[2] # Grabs the actual 3rd row layout entry

Absolute Integer Position Extraction (.iloc[2]):

Name    Dipto
ID         34
CGPA      3.7
Name: 2, dtype: object

In [217]:
# 4C. Dual-Axis Intersection Selection Queries (Slicing Specific Grid Quadrants)
# Syntax: dataframe.loc[row_labels][column_labels]
sub_grid_intersection = df_student_profile_with_header.loc[[1, 2]][["ID", "CGPA"]]
print("Quadrant Segment Intersection Lookup Result:")
sub_grid_intersection

Quadrant Segment Intersection Lookup Result:

   ID  CGPA
1  25   4.0
2  34   3.7

In [218]:
# ==============================================================================
# 5. MULTI-CRITERIA CONDITIONAL FILTERING PIPELINES
# ==============================================================================

print("--- Vectorized Multi-Criteria Boolean Filtering ---")

# Constructing a clean composite master dataframe profile
master_table_source = [
    ["Adar", 39, 3.30, 23],
    ["Jahid", 25, 4.00, 24],
    ["Dipto", 34, 3.70, 22]
]
master_column_labels = ["Name", "ID", "CGPA", "Age"] 
df_master_profile = pd.DataFrame(master_table_source, columns=master_column_labels)

# Executing strict vectorized conditional evaluation masking:
# Condition 1: Age metric column must evaluate strictly greater than 23
# Condition 2: CGPA performance column must evaluate strictly greater than 3.5
# Combined with the vector logical AND operator '&'
conditional_mask_filter = (df_master_profile["Age"] > 23) & (df_master_profile["CGPA"] > 3.5)
filtered_data_pipeline  = df_master_profile[conditional_mask_filter]

print("\nFinal Evaluated Data Extraction via Vectorized Masking:")
filtered_data_pipeline

--- Vectorized Multi-Criteria Boolean Filtering ---

Final Evaluated Data Extraction via Vectorized Masking:

    Name  ID  CGPA  Age
1  Jahid  25   4.0   24

In [73]:
"""
================================================================================
                    PANDAS COMPLETE MASTERY HANDBOOK (Part - 02)
                      Advanced Missing Data Cleaning Engines
================================================================================

Topics Covered:
---------------
✔ Missing Value Detection Systems (.isna, .sum, .any)
✔ Structural Row Elimination Rules (.dropna with dynamic thresholds)
✔ Uniform Blank Overwrites & Value Filling (.fillna)
✔ Smart Target Pipeline Replacements (Column-Specific Mapped Refills)
✔ Analytical Data Imputation Systems (Automated Statistical Means)
"""

import numpy as np
import pandas as pd

# ==============================================================================
# 1. ESTABLISHING THE UNCLEAN TARGET DATAFRAME
# ==============================================================================

# Generating an imperfect sample dataset containing raw NaN values
unclean_data_source = {
    "A": [1, 2, 3, 4, 5],
    "B": [1, 2, 3, 4, 5],
    "C": [1, 2, 3, np.nan, np.nan],
    "D": [1, np.nan, np.nan, np.nan, 5]
}

df_dirty = pd.DataFrame(unclean_data_source)

print("Original Unclean Data Profile:")
df_dirty

Original Unclean Data Profile:

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  NaN
2  3  3  3.0  NaN
3  4  4  NaN  NaN
4  5  5  NaN  5.0

In [219]:
# ==============================================================================
# 2. MISSING DATA AUDITING & DETECTION SCHEMAS
# ==============================================================================

print("\n--- Auditing Structural Missing Gaps ---")

# 2A. Element-wise Boolean Mask Generation (.isna)
# Evaluates every matrix grid element, flags missing elements as True
# If NAN, then true

boolean_null_mask = df_dirty.isna()

print("\nElement-Wise Null Boolean Matrix:")
boolean_null_mask

--- Auditing Structural Missing Gaps ---

Element-Wise Null Boolean Matrix:

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2  False  False  False   True
3  False  False   True   True
4  False  False   True  False

In [220]:
# 2B. Aggregated Vertical Frequency Metrics (.isna().sum())
# Automatically counts and displays total missing records down column channels

column_null_counts = df_dirty.isna().sum()
print("Missing Values Count Quantities Per Column:")
column_null_counts

Missing Values Count Quantities Per Column:

A    0
B    0
C    2
D    3
dtype: int64

In [221]:
# 4C. Structural Boolean Existence Verification Flags (.isna().any())
# Instantly alerts engineers if a column profile contains *at least one* blank cell

column_null_presence = df_dirty.isna().any()
print("Global Null Presence Flag Interceptions:")
column_null_presence

Global Null Presence Flag Interceptions:

A    False
B    False
C     True
D     True
dtype: bool

In [223]:
# ==============================================================================
# 3. ROW ELIMINATION WITH DYNAMIC THRESHOLDS (.dropna)
# ==============================================================================

print("--- Dropna Elimination Mechanics ---")

# 3A. Standard Aggressive Drop Execution (Drops row if ANY element is NaN)
df_aggressive_drop = df_dirty.dropna()

print("\nAggressive Rows Dropped (Only Pristine Records Kept):")
df_aggressive_drop

--- Dropna Elimination Mechanics ---

Aggressive Rows Dropped (Only Pristine Records Kept):

   A  B    C    D
0  1  1  1.0  1.0

In [224]:
# B. Using 'thresh' to Control Tolerance Limits
# 'thresh=x' sets a strict condition: rows MUST have at least 'x' NON-NAN elements to survive.

# 1. Lenient Threshold Rule (Requires at least 1 valid data cell to save row)
df_lenient_drop = df_dirty.dropna(thresh=1)

print("Dropped Rows Using Threshold = 1 (Lenient):")
df_lenient_drop

Dropped Rows Using Threshold = 1 (Lenient):

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  NaN
2  3  3  3.0  NaN
3  4  4  NaN  NaN
4  5  5  NaN  5.0

In [225]:
# 2. Unattainable Threshold Rule (Row dropped because no row has 5 valid cells)

df_over_strict_drop = df_dirty.dropna(thresh=5)

print("Dropped Rows Using Threshold = 5 (Impossible Criteria Matrix):")
df_over_strict_drop

Dropped Rows Using Threshold = 5 (Impossible Criteria Matrix):

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [226]:
# ==============================================================================
# 4. STATIC & TARGET-MAPPED REPLACEMENT PIPELINES (.fillna)
# ==============================================================================

print("--- Data Fillna Imputation Routines ---")

# 4A. Global Uniform Value Replacement
# Replaces every single encountered NaN value with a single static string fallback
df_blank_filled = df_dirty.fillna("NANA")

print("\nGlobally Substituted Static Strings Layout:\n")
df_blank_filled

--- Data Fillna Imputation Routines ---

Globally Substituted Static Strings Layout:

   A  B     C     D
0  1  1   1.0   1.0
1  2  2   2.0  NANA
2  3  3   3.0  NANA
3  4  4  NANA  NANA
4  5  5  NANA   5.0

In [113]:
# 4B. Precise Target Column Mapping Strategy
# Maps unique fallback (NaN) replacement configurations cleanly for specific columns

column_replacement_map = {'A': 0, 'B': 100, 'C': 300, 'D': 400}
df_mapped_fill = df_dirty.fillna(value=column_replacement_map)

print("Precisely Mapped Imputation Output:")
df_mapped_fill

Precisely Mapped Imputation Output:

   A  B      C      D
0  1  1    1.0    1.0
1  2  2    2.0  400.0
2  3  3    3.0  400.0
3  4  4  300.0  400.0
4  5  5  300.0    5.0

In [227]:
# ==============================================================================
# 5. AUTOMATED STATISTICAL MEAN IMPUTATION
# ==============================================================================

print("\n--- Automated Statistical Performance Mean Imputation ---")

"""
Imputing data with columns' respective statistical averages prevents loss 
of statistical volume while keeping downstream data distributions stable.
"""

# Dynamically calculates mathematical means for each independent numerical column 
# and automatically injects them back directly into matching column missing slots
df_imputed_mean = df_dirty.fillna(df_dirty.mean())

print("\nFinal Automated Analytical Columns Mean Overwrite:")
df_imputed_mean

--- Automated Statistical Performance Mean Imputation ---

Final Automated Analytical Columns Mean Overwrite:

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  3.0
2  3  3  3.0  3.0
3  4  4  2.0  3.0
4  5  5  2.0  5.0

In [88]:
"""
================================================================================
                    PANDAS COMPLETE MASTERY HANDBOOK (Part - 03)
                        Data Merging, Concatenation, & Joins
================================================================================

Topics Covered:
---------------
✔ Relational Database Merges (pd.merge: Inner, Outer, Left, Right)
✔ Axis-Based DataFrame Concatenation (pd.concat along Rows and Columns)
✔ Index-Based Data Combining Mechanics (.join engine configurations)
"""

import numpy as np
import pandas as pd

# ==============================================================================
# SETUP: PREPARING THE PRIMARY DATA LAYOUTS
# ==============================================================================

# Creating relational master dictionaries for relational joining models
employees_data = {
    'emp-id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
}
salaries_data = {
    'emp-id': [1, 2, 3, 16, 17],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
}

df_employees = pd.DataFrame(employees_data)
df_salaries = pd.DataFrame(salaries_data)

print("--- Data Layout Framework Profiles ---")

print("Employees DataFrame (Left):")
df_employees

--- Data Layout Framework Profiles ---
Employees DataFrame (Left):

   emp-id   name department
0       1   John         HR
1       2   Anna         IT
2       3  Peter    Finance
3       4  Linda         IT
4       5    Bob         HR

In [87]:
print("Salaries DataFrame (Right):")
df_salaries

Salaries DataFrame (Right):

   emp-id  salary  bonus
0       1   60000   5000
1       2   80000  10000
2       3   65000   7000
3      16   70000   8000
4      17   90000  12000

In [228]:
# ==============================================================================
# 1. SQL-STYLE DATABASE MERGING (pd.merge)
# ==============================================================================

print("\n--- Relational Database Merging Mechanics ---")

# 1A. Default Implicit Intersection Merge (Defaults to inner match on common keys)
df_default_merge = pd.merge(df_employees, df_salaries)

print("Default Merge (Implicit Keys Match):")
df_default_merge

--- Relational Database Merging Mechanics ---
Default Merge (Implicit Keys Match):

   emp-id   name department  salary  bonus
0       1   John         HR   60000   5000
1       2   Anna         IT   80000  10000
2       3  Peter    Finance   65000   7000

In [93]:
# 1B. Explicit Inner Merge (how='inner')
# Intersects keys; keeps rows ONLY where the key exists in BOTH DataFrames.
df_inner = pd.merge(df_employees, df_salaries, on="emp-id", how='inner')

print("Explicit Inner Merge Match:")
df_inner

Explicit Inner Merge Match:

   emp-id   name department  salary  bonus
0       1   John         HR   60000   5000
1       2   Anna         IT   80000  10000
2       3  Peter    Finance   65000   7000

In [95]:
# 1C. Full Outer Merge (how='outer')
# Unions keys; retains ALL records from both dataframes, filling mismatches with NaN.
df_outer = pd.merge(df_employees, df_salaries, on="emp-id", how='outer')

print("Full Outer Union Merge:")
df_outer

Full Outer Union Merge:

   emp-id   name department   salary    bonus
0       1   John         HR  60000.0   5000.0
1       2   Anna         IT  80000.0  10000.0
2       3  Peter    Finance  65000.0   7000.0
3       4  Linda         IT      NaN      NaN
4       5    Bob         HR      NaN      NaN
5      16    NaN        NaN  70000.0   8000.0
6      17    NaN        NaN  90000.0  12000.0

In [96]:
# 1D. Left Directional Merge (how='left')
# Keeps ALL rows from the Left DataFrame; pulls matching elements from the Right DataFrame.
df_left = pd.merge(df_employees, df_salaries, on="emp-id", how='left')

print("Left Directional Join Merge:")
df_left

Left Directional Join Merge:

   emp-id   name department   salary    bonus
0       1   John         HR  60000.0   5000.0
1       2   Anna         IT  80000.0  10000.0
2       3  Peter    Finance  65000.0   7000.0
3       4  Linda         IT      NaN      NaN
4       5    Bob         HR      NaN      NaN

In [97]:
# 1E. Right Directional Merge (how='right')
# Keeps ALL rows from the Right DataFrame; pulls matching elements from the Left DataFrame.
df_right = pd.merge(df_employees, df_salaries, on="emp-id", how='right')

print("Right Directional Join Merge:")
df_right

Right Directional Join Merge:

   emp-id   name department  salary  bonus
0       1   John         HR   60000   5000
1       2   Anna         IT   80000  10000
2       3  Peter    Finance   65000   7000
3      16    NaN        NaN   70000   8000
4      17    NaN        NaN   90000  12000

In [229]:
# ==============================================================================
# 2. AXIS-BASED STRUCTURAL CONCATENATION (pd.concat)
# ==============================================================================

print("--- Structural Stacking via pd.concat ---")

"""
pd.concat joins data assets along a specific physical grid axis direction.
- axis=0 (Rows): Stacks tables vertically on top of each other.
- axis=1 (Columns): Aligns tables horizontally side-by-side.
"""

component_a = {
    'A': ['a0', 'a1', 'a3'],
    'B': ['b0', 'b1', 'b3'], 
    'C': ['c0', 'c1', 'c3']
}
component_b = {
    'A': ['a4', 'a5', 'a6'],
    'B': ['b4', 'b5', 'b6'], 
    'C': ['c4', 'c5', 'c6']
}
df_comp1 = pd.DataFrame(component_a)
df_comp2 = pd.DataFrame(component_b)

# 2A. Vertical Row Stacking (axis=0)
df_v_concat = pd.concat([df_comp1, df_comp2])

print("\nVertical Concat Row Stacking (axis=0):")
df_v_concat

--- Structural Stacking via pd.concat ---

Vertical Concat Row Stacking (axis=0):

    A   B   C
0  a0  b0  c0
1  a1  b1  c1
2  a3  b3  c3
0  a4  b4  c4
1  a5  b5  c5
2  a6  b6  c6

In [100]:
# 4B. Horizontal Column Alignment Stacking (axis=1)
df_h_concat = pd.concat([df_comp1, df_comp2], axis=1)

print("Horizontal Concat Column Stacking (axis=1):")
df_h_concat

Horizontal Concat Column Stacking (axis=1):

    A   B   C   A   B   C
0  a0  b0  c0  a4  b4  c4
1  a1  b1  c1  a5  b5  c5
2  a3  b3  c3  a6  b6  c6

In [230]:
# ==============================================================================
# 3. INDEX-BASED MATRIX MERGING (DataFrame.join)
# ==============================================================================

print("\n--- Labeled Index-Based Join Operations ---")

"""
The .join() method links two DataFrames based primarily on their Index keys 
rather than explicitly named columns. It is cleaner and faster when combining 
datasets that are already aligned by custom indices.
"""

index_data_x = {"Name": ['Alice', 'Bob', 'Charlie']}
index_data_y = {"score": [85, 90, 75]}

df_indexed_x = pd.DataFrame(index_data_x, index=[1, 2, 3])
df_indexed_y = pd.DataFrame(index_data_y, index=[2, 3, 4])

# A. Outer Join Configuration (Combines all indices, fills gaps with NaN)
df_join_outer = df_indexed_x.join(df_indexed_y, how='outer')

print("\nIndex Outer Join Extraction:")
df_join_outer

--- Labeled Index-Based Join Operations ---

Index Outer Join Extraction:

      Name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [103]:
# B. Inner Join Configuration (Keeps only matching index rows)
df_join_inner = df_indexed_x.join(df_indexed_y, how='inner')

print("Index Inner Join Extraction:")
df_join_inner

Index Inner Join Extraction:

      Name  score
2      Bob     85
3  Charlie     90

In [104]:
"""
================================================================================
                    PANDAS COMPLETE MASTERY HANDBOOK (Part - 04)
                       Data Aggregations & GroupBy Mechanics
================================================================================

Topics Covered:
---------------
✔ The Split-Apply-Combine Lifecycles (.groupby)
✔ Multi-Axis Structured Aggregations (Grouping via Categorical Columns)
✔ Multi-Level Hierarchical Grouping Pipelines (Multi-Key Grouping Lists)
✔ Descriptive Statistical Summary Metrics (Standalone Aggregations)
✔ Descriptive Matrix Profiling Operations (.agg Mathematical Bundles)
"""

import numpy as np
import pandas as pd

# ==============================================================================
# SETUP: INITIALIZING MASTER TRANSACTION RECORDS
# ==============================================================================

transaction_records = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

df_sales_ledger = pd.DataFrame(transaction_records)

print("--- Base Transaction Ledger Profiles ---")
df_sales_ledger

--- Base Transaction Ledger Profiles ---

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [106]:
# ==============================================================================
# 1. GROUPBY ITERATION: DECONSTRUCTING THE SPLIT STAGE
# ==============================================================================

print("--- GroupBy Split Validation Loop ---")

"""
When executing .groupby(), Pandas partitions the data rows behind the scenes 
based on matching element keys (Split Phase) before any math calculations run.
"""

# Splitting the master data map using the unique items inside the 'Category' column
grouped_by_category = df_sales_ledger.groupby('Category')

# Iterating across the group engine returns the unique Key (i) and matching Sub-DataFrame (v)
for group_key, sub_dataframe in grouped_by_category:
    print(f"Active Extracted Group Key: [{group_key}]")
    print(sub_dataframe)
    print("-" * 45)

--- GroupBy Split Validation Loop ---
Active Extracted Group Key: [A]
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
---------------------------------------------
Active Extracted Group Key: [B]
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08
---------------------------------------------

In [108]:
# ==============================================================================
# 2. SINGLE-COLUMN CATEGORICAL AGGREGATIONS
# ==============================================================================

print("--- Single-Column Group Aggregations ---")

"""
Syntax Model: dataframe.groupby('Key_Column')['Target_Value_Column'].math_function()
This extracts specific segments and bundles summaries into a single series vector.
"""

category_sales_totals = df_sales_ledger.groupby('Category')['Sales'].sum()

print("Accumulated Sum of Sales per Category Group:")
category_sales_totals

--- Single-Column Group Aggregations ---
Accumulated Sum of Sales per Category Group:

Category
A    570
B    930
Name: Sales, dtype: int64

In [109]:
# ==============================================================================
# 3. MULTI-LEVEL HIERARCHICAL GROUPING PIPELINES
# ==============================================================================

print("\n--- 3. Multi-Level Hierarchical Grouping ---")

"""
By passing a list of distinct columns into the grouping engine, you generate 
a multi-layered MultiIndex row layout framework tracking combinations across variables.
"""

multi_level_sales_totals = df_sales_ledger.groupby(['Category', 'Store'])['Sales'].sum()

print("Hierarchical Sum of Sales per Category-Store Grid Combination:")
multi_level_sales_totals

--- 3. Multi-Level Hierarchical Grouping ---
Hierarchical Sum of Sales per Category-Store Grid Combination:

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [112]:
# 4. DATA SERIES MATRICES AND PROFILE MATRICES (.agg)
# ==============================================================================

print("\n--- Standalone and Bundled Aggregation Profiles ---")

# A. Standard isolated analytical operations over flat vectors
flat_sales_average = df_sales_ledger['Sales'].mean()
print(f"Global Mathematical Average Sales Scalar: {flat_sales_average}") # Output: 187.5

# B. Multi-Metric Descriptive Performance Bundles (.agg())
# Passing a list of statistical functions directly computes multiple metrics at once,
# building a comprehensive summary matrix panel from a raw data column.
sales_comprehensive_profile = df_sales_ledger['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])

print("\nComprehensive Bundled Summary Calculations Matrix:")
sales_comprehensive_profile

--- Standalone and Bundled Aggregation Profiles ---
Global Mathematical Average Sales Scalar: 187.5

Comprehensive Bundled Summary Calculations Matrix:

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

In [114]:
"""
================================================================================
                    PANDAS COMPLETE MASTERY HANDBOOK (Part - 05)
                          Pivot Tables & Crosstab Engines
================================================================================

Topics Covered:
---------------
✔ DateTime Metadata Extraction Methods (.dt.month_name & .dt.quarter)
✔ Multi-Dimensional Matrix Reshaping via pd.pivot_table()
✔ Custom Operational Aggregations ('median', 'mean' over multiple values)
✔ Categorical Structural Frequency Auditing via pd.crosstab()
"""

import numpy as np
import pandas as pd

# Setting seed value to lock down static synthetic value distributions
np.random.seed(42)

# ==============================================================================
# SETUP: DATETIME INFLATION AND SOURCE DATAFRAME GENERATION
# ==============================================================================

raw_ledger_data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South'] * 5,
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice'] * 5
}

df_source = pd.DataFrame(raw_ledger_data)

# Extracting temporal string characteristics from Series timestamp elements via .dt accessor
df_source['Month'] = df_source['Date'].dt.month_name()
df_source['Quarter'] = 'Q' + df_source['Date'].dt.quarter.astype(str)

print("---  Inflated Master Dataset View ---")
df_source.head(5)

---  Inflated Master Dataset View ---

        Date Product Region  Sales  Units    Rep    Month Quarter
0 2023-01-01       A   East    202     31   John  January      Q1
1 2023-01-02       B   West    535     62   Mary  January      Q1
2 2023-01-03       C  North    960     11    Bob  January      Q1
3 2023-01-04       D  South    370     97  Alice  January      Q1
4 2023-01-05       A   East    206     39   John  January      Q1

In [116]:
# ==============================================================================
# 1. THE RESHAPING ENGINE: PANDAS PIVOT TABLES (pd.pivot_table)
# ==============================================================================

print("\n--- Structural Reshaping via Pivot Tables ---")

"""
CRITICAL COMPREHENSION RULES:
-----------------------------
1. 'index':   Determines the row labels of the final reshaped matrix table.
2. 'columns': Determines the column headings of the final reshaped matrix table.
3. 'values':  The target numeric measurement columns being aggregated.
4. 'aggfunc': Mathematical engine used to compress matching data groups (defaults to 'mean').

Data Integrity Requirement:
---------------------------
The column assigned to 'values' must strictly contain numeric data. 
Passing non-numeric columns like strings, names, or text labels into a 
mathematical 'aggfunc' framework will throw an explicit handling Exception.
"""

# 1A. Reshaping with a Custom Single Aggregation Metric ('median')
pivot_median_sales = pd.pivot_table(
    data=df_source,
    values="Sales",
    index="Region",
    columns="Product",
    aggfunc="median"
)

print("Pivot Table: Median Sales across Product x Region Matrix:")
pivot_median_sales

--- Structural Reshaping via Pivot Tables ---
Pivot Table: Median Sales across Product x Region Matrix:

Product      A      B      C      D
Region
East     206.0    NaN    NaN    NaN
North      NaN    NaN  763.0    NaN
South      NaN    NaN    NaN  314.0
West       NaN  535.0    NaN    NaN

In [117]:
# 1B. Multi-Value Multi-Layered Dimension Reshaping
# Passing a list of numeric features generates a hierarchically structured multi-index column layout grid
pivot_multi_metric = pd.pivot_table(
    data=df_source,
    values=['Sales', 'Units'],
    index='Region',
    columns='Product',
    aggfunc='mean'
)

print("Hierarchical Pivot Table: Mean Metrics Matrix Across Product-Region Axises:")
pivot_multi_metric

Hierarchical Pivot Table: Mean Metrics Matrix Across Product-Region Axises:

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     350.2    NaN    NaN    NaN  54.8   NaN   NaN   NaN
North      NaN    NaN  655.2    NaN   NaN   NaN  46.2   NaN
South      NaN    NaN    NaN  301.2   NaN   NaN   NaN  80.4
West       NaN  491.2    NaN    NaN   NaN  44.2   NaN   NaN

In [118]:
# ==============================================================================
# 2. CATEGORICAL FREQUENCY ANALYSES (pd.crosstab)
# ==============================================================================

print("--- Frequency Distribution via Contingency Tables ---")

"""
pd.crosstab() computes a frequency contingency map that displays the raw element 
co-occurrence counts across distinct structural groupings or categories.
"""

# Tabulates interaction event volumes between regions and products
contingency_frequency_matrix = pd.crosstab(
    index=df_source['Region'],
    columns=df_source['Product']
)

print("Frequency Count Crosstab Matrix Allocation:")
contingency_frequency_matrix

--- Frequency Distribution via Contingency Tables ---
Frequency Count Crosstab Matrix Allocation:

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [119]:
"""
================================================================================
                    PANDAS COMPLETE MASTERY HANDBOOK (Part - 06)
                     Metadata Auditing & Custom Function Mapping
================================================================================

Topics Covered:
---------------
✔ Structural Shape Verification Attributes (.shape)
✔ Information and Memory Overhead Audits (.info())
✔ Summary Distribution Matrices (.describe())
✔ Vectorized Series Column Transformations
✔ Functional Row/Element Custom Transformations (.apply via Vectorized Lambdas)
"""

import numpy as np
import pandas as pd

# ==============================================================================
# SETUP: PREPARING THE CORE METRIC DATAFRAME
# ==============================================================================

# Initializing base aligned analytical data assets
base_metrics_source = {
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
}

df_metrics = pd.DataFrame(base_metrics_source)
print("--- Base Matrix Entry View ---")
df_metrics

--- Base Matrix Entry View ---

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [126]:
# ==============================================================================
# 1. STRUCTURAL META AUDITING (.shape, .info, .describe)
# ==============================================================================

print("--- Structural Meta Auditing Pipelines ---")

# 1A. Dimensional Boundary Verification Tuple (.shape)
# Returns a strict dimensional count snapshot format: (Total Rows, Total Columns)
print(f"\nDataFrame Shape Demarcation Boundaries: {df_metrics.shape}")

# 1B. Internal System Architecture and Memory Diagnostics Summary (.info())
# Instantly prints structural index ranges, column non-null data volume counts, 
# explicit type assignments (dtypes), and runtime memory block footprints.
print("\nSystem Architecture Diagnostic Summary:")
df_metrics.info()

--- Structural Meta Auditing Pipelines ---

DataFrame Shape Demarcation Boundaries: (5, 3)

System Architecture Diagnostic Summary:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [127]:
# 1C. Summary Distribution Statistical Matrix (.describe())
# Provides key descriptive statistical breakdowns over numeric elements, 
# automatically calculating averages, standard deviations, and quartile cutoffs.
print("Summary Distribution Statistical Calculations Matrix:")
df_metrics.describe()

Summary Distribution Statistical Calculations Matrix:

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [136]:
# ==============================================================================
# 2. IN-PLACE VECTORIZED ELEMENT BROADCASTING
# ==============================================================================

print("---  Vectorized Column Modifications ---")

"""
Just like NumPy arrays, Pandas Series execute vectorized math natively. 
Adding a scalar to a Series broadcasts the operation across all row elements instantly.
"""

# Overwriting existing Column 'A' data elements by broadcasting an addition operation
df_metrics['A'] = df_metrics['A'] + 10

print("Mutated Broadcasted Column 'A' Extraction:")
df_metrics['A']

---  Vectorized Column Modifications ---
Mutated Broadcasted Column 'A' Extraction:

0    21
1    22
2    23
3    24
4    25
Name: A, dtype: int64

In [135]:
# ==============================================================================
# 3. CUSTOM ELEMENT MAPPING OPERATIONS (.apply via Lambdas)
# ==============================================================================

print("---  Custom Function Mapping Engines ---")

"""
The .apply() method lets you run custom data transformations across rows or columns.
When paired with an inline lambda function, it maps a custom operation over each 
element in a data channel without slow, explicit Python loops.
"""

# Generating a new Column 'D' feature vector by isolating Column 'B' elements
# and squaring each value via an inline anonymous lambda function pipeline
df_metrics['D'] = df_metrics["B"].apply(lambda individual_element : individual_element ** 2)

print("Final Mutated DataFrame State Matrix with Custom Mapped Inflation:")
df_metrics

---  Custom Function Mapping Engines ---
Final Mutated DataFrame State Matrix with Custom Mapped Inflation:

    A   B    C     D
0  11  10  100   100
1  12  20  200   400
2  13  30  300   900
3  14  40  400  1600
4  15  50  500  2500

In [131]:
"""
================================================================================
                    PANDAS COMPLETE MASTERY HANDBOOK (Part - 07)
                      Advanced Text Parsing & Feature Ingestion
================================================================================

Topics Covered:
---------------
✔ Production File Ingestion Engines (pd.read_csv with Raw String Paths)
✔ Dynamic Feature Extraction Pipelines via Targeted Text Loops
✔ Element-wise String Sanitization Metaprogramming (.str.replace)
✔ Architectural Data Type Casting Configurations (.astype)
✔ Logical Boolean Filtering Matrix Isolations (Max Metric Identifications)
"""

import numpy as np
import pandas as pd

# ==============================================================================
# 1. FILE INGESTION & MASTER ARCHITECTURE DATA SNAPSHOT
# ==============================================================================

print("--- Production Storage File Ingestion ---")

# Ingesting raw local unstructured tabular files using raw string literal 'r' paths
# to bypass operating system escape characters safely
df_anime = pd.read_csv(r'Anime.csv')

# Inspecting the top 5 records of our initial ingestion matrix
print("\nBase Top 5 Records Grid View:")
df_anime.head(5)

--- 1. Production Storage File Ingestion ---

Base Top 5 Records Grid View:

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [132]:
# Verifying individual element positioning values using label-based lookup properties (.loc)
print("\nIsolating Target Row Index 3 Text Data String:")
print(df_anime.loc[3]['Title'])

Isolating Target Row Index 3 Text Data String:
Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members

In [133]:
# ==============================================================================
# 2. FEATURE EXTRACTION STAGE 1: EPISODE COUNT SEGMENTATION
# ==============================================================================

print("--- Custom Element Text Parsing: Episode Extraction ---")

def extract_episode_metadata(target_text_string):
    """
    Scans a raw unformatted text stream row element to capture and isolate
    the text character sequence nested exclusively inside standard parentheses.
    """
    capture_active = False
    extracted_buffer = ""
    
    for character in target_text_string:
        if character == ')':
            capture_active = False
        if capture_active == True:
            extracted_buffer = extracted_buffer + character
        if character == '(':
            capture_active = True
            
    return extracted_buffer

# Executing structural feature inflation by mapping our custom parser engine
# across the 'Title' Series column lanes using functional element mapping (.apply)
df_anime['Episodes'] = df_anime['Title'].apply(extract_episode_metadata)

print("\nInflated Matrix with Isolated Episode Text Elements:")
df_anime[['Title', 'Episodes']].head(5)

--- Custom Element Text Parsing: Episode Extraction ---

Inflated Matrix with Isolated Episode Text Elements:

                                               Title Episodes
0  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   64 eps
1  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   24 eps
2  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   13 eps
3  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   51 eps
4  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   10 eps

In [142]:
# ==============================================================================
# 3. DATA CLEANING & EXPLICIT DTYPE CASTING CONVERSIONS
# ==============================================================================

print("--- Element Sanitization & Data Type Casting ---")

# Removing non-numeric string labels via vectorized string character replacements
df_anime['Episodes'] = df_anime['Episodes'].str.replace(" eps", "")

# Converting string metadata representations into pure structural mathematical integers (.astype)
df_anime['Episodes'] = df_anime['Episodes'].astype(int)

print("\nSanitized Numeric Data Frames Type Verification Summary:")
print(df_anime[['Title', 'Episodes']].dtypes)

--- Element Sanitization & Data Type Casting ---

AttributeError: Can only use .str accessor with string values!

In [141]:
# ==============================================================================
# 4. ADVANCED PATTERN EXTRACTION: DATE RANGE SEGMENTATION
# ==============================================================================

print("--- Complex Feature Isolation: Extracting Time Ranges ---")

def extract_time_metadata(target_text_string):
    """
    Parses unformatted cell strings to isolate the temporal date sequences.
    Finds the closing parenthesis boundary and extracts the tracking date ranges 
    running up to the dynamic 'members' string sequence cutoff point.
    """
    # Locating precise text boundary indices inside the data channel
    parenthesis_close_index = target_text_string.find(')')
    member_keyword_index = target_text_string.find('members')
    
    # If the structural string boundary markers are not detected, return a safe fallback value
    if parenthesis_close_index == -1 or member_keyword_index == -1:
        return np.nan
        
    # Slicing the exact target string subset residing between the structural boundaries
    raw_date_segment = target_text_string[parenthesis_close_index + 1 : member_keyword_index]
    
    # Cleaning up trailing numbers leftover from user count metadata blocks
    cleaned_date_segment = ""
    for character in raw_date_segment:
        # Stop tracking the string immediately if it hits the user membership count digits
        if character.isdigit() and not cleaned_date_segment[-1:].isdigit() and not cleaned_date_segment[-4:].strip().replace("-","").isdigit():
            # Looks ahead to check if the integer belongs to a calendar year string sequence
            pass 
        cleaned_date_segment = cleaned_date_segment + character
        
    # Final trim to eliminate any numeric overflows or structural artifacts
    import re
    # Match patterns like 'Apr 2009 - Jul 2010' specifically, truncating garbage metadata trailing behind it
    date_match = re.search(r'[A-Za-z]{3}\s+\d{4}\s*-\s*[A-Za-z]{3}\s+\d{4}', cleaned_date_segment)
    if date_match:
        return date_match.group(0)
        
    # Secondary match pattern rule for unique single-day movie premiere dates (e.g., 'Jan 2021 - Jan 2021')
    movie_match = re.search(r'[A-Za-z]{3}\s+\d{4}', cleaned_date_segment)
    if movie_match:
        return movie_match.group(0)
        
    return cleaned_date_segment.strip()

# Inflating the DataFrame with the extracted temporal tracking schedules 
df_anime['Time_Range'] = df_anime['Title'].apply(extract_time_metadata)

print("\nDataFrame View with Labeled Clean Matrix Intersections:")
df_anime[['Title', 'Episodes', 'Time_Range']].head(5)

--- Complex Feature Isolation: Extracting Time Ranges ---

DataFrame View with Labeled Clean Matrix Intersections:

,Title,Episodes,Time_Range
0,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,64,Apr 2009 - Jul 2010
1,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",24,Apr 2011 - Sep 2011
2,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,13,Oct 2022 - Dec 2022
3,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",51,Apr 2015 - Mar 2016
4,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,10,Apr 2019 - Jul 2019

In [144]:
# ==============================================================================
# 5. DATA CRITERIA FILTERS: HIGHEST SCORE METRIC IDENTIFICATION
# ==============================================================================

print("--- Target Boolean Mask Profiling Queries ---")

# Creating a boolean conditional evaluation array comparing row entries against the max score vector
boolean_maximum_mask = df_anime['Score'] == df_anime['Score'].max()

# Filtering the data frame matrix using the mask vector to isolate target values
highest_rated_anime_titles = df_anime[boolean_maximum_mask]['Title']

print("Isolating Title Record Hosting the Maximum Numerical Score Metric:")
highest_rated_anime_titles

--- Target Boolean Mask Profiling Queries ---
Isolating Title Record Hosting the Maximum Numerical Score Metric:

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: object

In [146]:
"""
================================================================================
                    PANDAS COMPLETE MASTERY HANDBOOK (Part - 08)
                     Advanced Data Auditing, Filtering, & Sorting
================================================================================

Topics Covered:
---------------
✔ Structural Boundary Diagnostics & Metadata Extraction (.shape, .columns)
✔ High-Performance Sorting Architectures (.sort_values, ascending=False)
✔ Categorical Value Distribution Audits (.value_counts(), .count())
✔ Conditional Positional Slicing Indexing (.nlargest(), .iloc[])
✔ Advanced Missing Vector Profiling (.isna().sum())
✔ Custom String Token Scanning Pipelines (.apply() Vector Optimization)
✔ Multi-Level Regional Condition Segment Filtering (Boolean Mask Unions)
"""

import numpy as np
import pandas as pd

# ==============================================================================
# SETUP: PREPARING MOCK COMPRESSED METRIC DATAFRAME ASSET FOR TESTING
# ==============================================================================


print("--- Ingestion & Initial Boundary Auditing ---")
# Reading unstructured data files using standardized file system ingestion engines

df = pd.read_csv("Countries.csv") 

# A. Tracking strict horizontal and vertical dimensional array boundaries (.shape)
print(f"\nData Grid Shape Vector: {df.shape}") 

# B. Tracking explicit structural field keys (.columns)
print(f"\nExtracted Structural Table Features Array: {list(df.columns)}")

--- Ingestion & Initial Boundary Auditing ---

Data Grid Shape Vector: (194, 64)

Extracted Structural Table Features Array: ['country', 'country_long', 'currency', 'capital_city', 'region', 'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land', 'forest_area', 'land_area', 'rural_land', 'urban_land', 'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp', 'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp', 'unemployment_pct', 'vulnerable_employment_pct', 'electricity_access_pct', 'alternative_nuclear_energy_pct', 'electricty_production_coal_pct', 'electricty_production_hydroelectric_pct', 'electricty_production_gas_pct', 'electricty_production_nuclear_pct', 'electricty_production_oil_pct', 'electricty_production_renewable_pct', 'energy_imports_pct', 'fossil_energy_consumption_pct', 'renewable_energy_consumption_pct', 'co2_emissions', 'methane_emissions', 'nitrous_oxide_emissions', 'greenhouse_other_emissions', 'urban_population_under_5m', 'health_expenditure_pct_gdp', 'health_expenditure_capita', 'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces', 'internally_displaced_persons', 'military_expenditure_pct_gdp', 'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct', 'life_expectancy', 'net_migration', 'population_female', 'population_male', 'population', 'women_parliament_seats_pct', 'rural_population', 'urban_population', 'press', 'democracy_score', 'democracy_type', 'median_age', 'political_leader', 'title']

In [149]:
# ==============================================================================
# 2. GLOBAL MAXIMUM VALUE METRIC FILTERS
# ==============================================================================

print("\n---  Global Metric Maximum Isolations ---")

"""
Boolean masks identify records matching precise criteria. By comparing a series 
to its absolute maximum value, we filter the dataframe to expose the peak record.
"""

# Generating structural boolean indicator filters mapping maximum population sets
boolean_max_pop_mask = df['population'] == df['population'].max()
boolean_max_pop_mask

---  Global Metric Maximum Isolations ---

0      False
1      False
2      False
3      False
4      False
       ...
189    False
190    False
191    False
192    False
193    False
Name: population, Length: 194, dtype: bool

In [150]:
# 2A. Isolating the complete descriptive horizontal row profile matching the criteria
df_max_pop_record = df[boolean_max_pop_mask]

print("Complete Record for Highest Populated Global Entity:")
df_max_pop_record

Complete Record for Highest Populated Global Entity:

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.0,77.0,1790450.0,...,1417173173,14.9446,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister

In [151]:
# 2B. Extracting targeted text series attributes via single-column lane isolations
peak_country_name = df[boolean_max_pop_mask]['country'].values[0]
peak_capital_city = df[boolean_max_pop_mask]['capital_city'].values[0]

print(f"Isolated Country: {peak_country_name} | Labeled Capital Capital: {peak_capital_city}")

Isolated Country: India | Labeled Capital Capital: New Delhi

In [153]:
# ==============================================================================
# 3. QUANTILE STRUCTURAL SORTING & SUBSET PROCESSING
# ==============================================================================

print("\n---  Performance Vector Sorting Structures ---")

"""
Sorting rows by a numeric metric arranges data cleanly. By disabling ascending sort,
the highest scores rise to the top, allowing easy extraction of the peak records.
"""

# Re-indexing rows permanently in-place by a target numeric vector in descending layout order
df.sort_values(by='democracy_score', ascending=False, inplace=True)

# Slicing the top 5 records of our sorted framework to extract the target subset lane
top_democracy_entities = df['country'].head(5)
print("\nTop 5 Countries Sorted by Democratic Index Performance Matrix:")
top_democracy_entities

---  Performance Vector Sorting Structures ---

Top 5 Countries Sorted by Democratic Index Performance Matrix:

127         Norway
74         Iceland
164         Sweden
122    New Zealand
46         Denmark
Name: country, dtype: object

In [155]:
# ==============================================================================
# 4. CATEGORICAL CROSS-DISTRIBUTION AUDITS
# ==============================================================================

print("---  Categorical Frequency Distribution Profiles ---")

"""
Value count engines summarize unique categorical values. Running mathematical
aggregations on these summary blocks uncovers distribution statistics instantly.
"""

# Calculating unique value distribution frequencies down a target column series
regional_frequency_counts = df['region'].value_counts()
print("\nTotal Item Volume Frequency Distribution Over Regional Groupings:\n", regional_frequency_counts)

# Evaluating the absolute aggregate number of distinct regional group entries
total_distinct_regions = df['region'].value_counts().count()
print(f"\nTotal Isolated Regional Groups Present inside DataFrame: {total_distinct_regions}")

---  Categorical Frequency Distribution Profiles ---

Total Item Volume Frequency Distribution Over Regional Groupings:
 region
Western Asia                 17
Eastern Africa               17
Western Africa               16
Southern Europe              15
Caribbean                    13
South America                12
South-Eastern Asia           11
Middle Africa                10
Eastern Europe               10
Northern Europe              10
Southern Asia                 9
Western Europe                9
Central America               8
Northern Africa               6
Southern Africa               5
Eastern Asia                  5
Central Asia                  5
Micronesia                    5
Melanesia                     4
Polynesia                     3
Australia and New Zealand     2
Northern America              2
Name: count, dtype: int64

Total Isolated Regional Groups Present inside DataFrame: 22

In [156]:
# ==============================================================================
# 5. REGIONAL SUBSET MASKING INTERSECTIONS
# ==============================================================================

print("--- 5. Regional Mask Intersections ---")

# A. Isolating value distribution frequency totals matching a tracking label string
eastern_europe_count = df['region'].value_counts()['Eastern Europe']
print(f"\nTotal Numerical Volume Frequency Mapping to 'Eastern Europe': {eastern_europe_count}")
# Output: Total Numerical Volume Frequency Mapping to 'Eastern Europe': 10

# B. Generating a boolean condition filter array targeting a specific region string
boolean_eastern_europe_mask = df['region'] == "Eastern Europe"

# C. Extracting complete records and target sub-column attributes matching the condition
df_eastern_europe = df[boolean_eastern_europe_mask]
eastern_europe_countries = df[boolean_eastern_europe_mask]['country']

print("\nExtracted Eastern European Tabular Sub-Matrix Intersection View:")
df_eastern_europe

--- 5. Regional Mask Intersections ---

Total Numerical Volume Frequency Mapping to 'Eastern Europe': 10

Extracted Eastern European Tabular Sub-Matrix Intersection View:

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
43,Czech Republic,Czech Republic,Czech koruna,Prague,Eastern Europe,Europe,Czech,49.750000,15.5,35238.7,...,10526073,25.5000,2697096,7828977,3.14,7.69,Flawed democracy,38.8,Andrej Babiš,Prime Minister
151,Slovak Republic,Slovak Republic,Euro,Bratislava,Eastern Europe,Europe,Slovak,48.666667,19.5,18830.0,...,5431752,21.3333,2503549,2928203,3.32,7.10,Flawed democracy,36.0,NaN,NaN
24,Bulgaria,Republic of Bulgaria,Bulgarian lev,Sofia,Eastern Europe,Europe,Bulgarian,43.000000,25.0,50470.0,...,6465097,24.1667,1528155,4936942,2.23,7.03,Flawed democracy,40.7,Boyko Borisov,Prime Minister
136,Poland,Republic of Poland,Polish zloty,Warsaw,Eastern Europe,Europe,Polish,52.000000,20.0,144610.0,...,37561599,28.2609,14974307,22587292,2.71,6.67,Flawed democracy,36.3,Mateusz Morawiecki,Prime Minister
73,Hungary,Hungary,Hungarian forint,Budapest,Eastern Europe,Europe,Hungarian,47.000000,20.0,49030.0,...,9683505,14.0704,2657928,7025577,2.57,6.63,Flawed democracy,38.1,Viktor Orbán,Prime Minister
139,Romania,Romania,New Romanian leu,Bucharest,Eastern Europe,Europe,Romanian,46.000000,25.0,135910.0,...,18956666,19.0909,8627368,10329298,3.05,6.38,Flawed democracy,37.4,Klaus Iohannis,President
111,Moldova,Republic of Moldova,Moldovan leu,Chișinău,Eastern Europe,Europe,Moldovan,47.000000,29.0,22646.0,...,2592477,40.5941,1473227,1119250,2.51,5.85,Hybrid regime,31.2,Ion Chicu,Prime Minister
181,Ukraine,Ukraine,Ukrainian hryvnia,Kiev,Eastern Europe,Europe,Ukrainian,49.000000,32.0,413110.0,...,38000000,20.3310,11430780,26569220,2.41,5.69,Hybrid regime,38.9,Volodymyr Zelensky,President
14,Belarus,Republic of Belarus,Belarusian rubel,Minsk,Eastern Europe,Europe,Belarusian,53.000000,28.0,82810.0,...,9208701,40.0000,1811720,7396981,1.51,3.13,Authoritarian,36.5,Alexander Lukashenko,President
140,Russia,Russian Federation,Russian ruble,Moscow,Eastern Europe,Europe,Russian,60.000000,100.0,2154940.0,...,143555736,16.2222,35708054,107847682,1.55,2.94,Authoritarian,35.0,Vladimir Putin,President

In [157]:
print("Isolated Country Series Listing:")
eastern_europe_countries

Isolated Country Series Listing:

43      Czech Republic
151    Slovak Republic
24            Bulgaria
136             Poland
73             Hungary
139            Romania
111            Moldova
181            Ukraine
14             Belarus
140             Russia
Name: country, dtype: object

In [159]:
# ==============================================================================
# 6. RELATIVE POSITION POSITION DATA SLICING (.nlargest)
# ==============================================================================

print("\n--- Relational Coordinate Slicing Via nlargest Pipelines ---")

"""
Finding values at specific ranks can trigger indexing errors if rows are out of order.
Combining .nlargest() with position-based slicing (.iloc) isolates specific ranks perfectly.
"""

# Isolating the exact numerical threshold representing the 2nd largest value position
target_second_highest_value = df['population'].nlargest(2).iloc[1]

# Generating a boolean mask tracking row items matching our precise target threshold value
boolean_second_pop_mask = df['population'] == target_second_highest_value

# Extracting the target feature value associated with the verified data record
target_leader_identity = df[boolean_second_pop_mask]['political_leader'].values[0]
print(f"Political Leader of the 2nd Highest Populated Entity (India Reference Check): {target_leader_identity}")

--- Relational Coordinate Slicing Via nlargest Pipelines ---
Political Leader of the 2nd Highest Populated Entity (India Reference Check): Xi Jinping

In [161]:
# ==============================================================================
# 7. NULL MASK FREQUENCY SEARCHES
# ==============================================================================

print("--- Missing Value Matrix Profile Tracking ---")

# Mapping an element-wise boolean null verification layout tracking vector (.isna())
print("\nElement-wise Null Boolean Mask Matrix Tracking:")
df['political_leader'].isna().head(5)

--- Missing Value Matrix Profile Tracking ---

Element-wise Null Boolean Mask Matrix Tracking:

127    False
74     False
164    False
122    False
46     False
Name: political_leader, dtype: bool

In [162]:
# Isolating data segments matching the mask to run rapid record accumulation counts
total_unverified_leaders_count = df[df['political_leader'].isna()]['country'].count()
print(f"Total Tracked Entity Rows Hosting Unverified/Unknown Political Leaders: {total_unverified_leaders_count}")

Total Tracked Entity Rows Hosting Unverified/Unknown Political Leaders: 7

In [163]:
# ==============================================================================
# 8. STRING TOKEN OPERATIONS VIA CUSTOM MAPPING LOOPS
# ==============================================================================

print("--- Text Token Analysis and Pattern Auditing ---")

"""
Standard text loops can use global counters to track patterns across rows.
Pandas processes these cleanly using custom element mapping functions (.apply).
"""

# Initializing global tracking variable assets
global_matching_keyword_counter = 0

def scan_text_token_patterns(target_input_text):
    """
    Evaluates individual row text records to detect target string combinations, 
    updating tracking counters whenever a match is validated.
    """
    global global_matching_keyword_counter
    
    # Standardizing incoming text streams to lowercase to avoid case-sensitivity misses
    if 'republic' in str(target_input_text).lower():
        global_matching_keyword_counter += 1
        
    return target_input_text

# Processing text parsing patterns across columns via functional element mapping (.apply)
df['country_long'].apply(scan_text_token_patterns)
print(f"Total Validated Country Titles Hosting the Token 'republic': {global_matching_keyword_counter}")

--- Text Token Analysis and Pattern Auditing ---
Total Validated Country Titles Hosting the Token 'republic': 125

In [164]:
# ==============================================================================
# 9. DUAL-CONDITIONAL REGIONAL MAX FILTERS
# ==============================================================================

print("--- Segmented Intersections: Regional Maximum Filters ---")

"""
To isolate maximum metrics within specific regions, first generate a separate 
regional sub-dataframe. Then, evaluate maximum attributes within that filtered subset.
"""

# 9A. Isolating a targeted geographic segment to build a regional sub-dataframe
boolean_africa_continent_mask = df['continent'] == 'Africa'
df_african_continent_segment = df[boolean_africa_continent_mask]
print("\nIsolated Regional African Segment Sub-DataFrame:")
df_african_continent_segment

--- Segmented Intersections: Regional Maximum Filters ---

Isolated Regional African Segment Sub-DataFrame:

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
108,Mauritius,Republic of Mauritius,Mauritian rupee,Port Louis,Eastern Africa,Africa,Mauritian,-20.283333,57.550000,860.0,...,1262523,20.00000,747287,515236,2.75,8.22,Full democracy,33.1,Pravind Jugnauth,Prime Minister
27,Cabo Verde,Republic of Cabo Verde,Cabo Verde escudo,Praia,Western Africa,Africa,Cape Verdian,16.000000,-24.000000,790.0,...,593149,38.88890,192507,400642,3.95,7.88,Flawed democracy,22.9,NaN,NaN
21,Botswana,Republic of Botswana,Botswana pula,Gaborone,Southern Africa,Africa,Motswana,-22.000000,24.000000,258620.0,...,2630296,11.11110,730591,1899705,3.12,7.81,Flawed democracy,19.7,Mokgweetsi Masisi,President
155,South Africa,Republic of South Africa,South African rand,Pretoria,Southern Africa,Africa,South African,-29.000000,24.000000,963410.0,...,59893885,46.50000,18965399,40928486,3.52,7.24,Flawed democracy,23.3,Cyril Ramaphosa,President
94,Lesotho,Kingdom of Lesotho,Lesotho loti,Maseru,Southern Africa,Africa,Mosotho,-29.500000,28.500000,26000.0,...,2305825,26.44630,1615392,690433,2.63,6.64,Flawed democracy,18.2,Tom Thabane,Prime Minister
64,Ghana,Republic of Ghana,New Ghanaian cedi,Accra,Western Africa,Africa,Ghanaian,8.000000,-2.000000,126037.0,...,33475870,14.54550,13853989,19621881,3.76,6.63,Flawed democracy,16.6,Nana Akufo-Addo,President
176,Tunisia,Republic of Tunisia,Tunisian dinar,Tunis,Northern Africa,Africa,Tunisian,34.000000,9.000000,97310.0,...,12356117,26.26730,3680393,8675724,2.64,6.41,Flawed democracy,28.0,Kaïs Saïed,President
118,Namibia,Republic of Namibia,Namibian dollar,Windhoek,Southern Africa,Africa,Namibian,-22.000000,17.000000,388100.0,...,2567012,44.23080,1181955,1385057,4.13,6.25,Flawed democracy,17.4,Hage Geingob,President
146,Senegal,Republic of Senegal,West African CFA franc,Dakar,Western Africa,Africa,Senegalese,14.000000,-14.000000,88780.0,...,17316449,44.24240,8816497,8499952,3.03,6.15,Flawed democracy,14.0,Macky Sall,President
17,Benin,Republic of Benin,West African CFA franc,Porto-Novo,Western Africa,Africa,Beninese,9.500000,2.250000,39500.0,...,13352864,7.40741,6738656,6614208,2.46,5.74,Hybrid regime,13.6,Patrice Talon,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
101,Malawi,Republic of Malawi,Malawi kwacha,Lilongwe,Eastern Africa,Africa,Malawian,-13.500000,34.000000,56500.0,...,20405317,22.91670,16736441,3668876,2.66,5.49,Hybrid regime,13.1,Peter Mutharika,President
104,Mali,Republic of Mali,West African CFA franc,Bamako,Western Africa,Africa,Malian,17.000000,-4.000000,412010.0,...,22593590,28.57140,12327741,10265849,2.22,5.41,Hybrid regime,11.3,Ibrahim Boubacar Keïta,President
168,Tanzania,United Republic of Tanzania,Tanzanian shilling,Dodoma,Eastern Africa,Africa,Tanzanian,-6.000000,35.000000,395212.0,...,65497748,36.85570,41471864,24025884,2.16,5.41,Hybrid regime,13.0,John Magufuli,President
95,Liberia,Republic of Liberia,U.S. dollar,Monrovia,Western Africa,Africa,Liberian,6.500000,-9.500000,19540.4,...,5302681,10.95890,2488813,2813868,2.48,5.35,Hybrid regime,14.2,George Weah,President
100,Madagascar,Republic of Madagascar,Malagasy ariary,Antananarivo,Eastern Africa,Africa,Malagasy,-20.000000,47.000000,408950.0,...,29611714,18.54300,17801970,11809744,2.82,5.22,Hybrid regime,15.1,Andry Rajoelina,President
180,Uganda,Republic of Uganda,Ugandan shilling,Kampala,Eastern Africa,Africa,Ugandan,1.000000,32.000000,144150.0,...,47249585,33.81300,34889566,12360019,1.98,5.20,Hybrid regime,12.2,Yoweri Museveni,President
86,Kenya,Republic of Kenya,Kenyan shilling,Nairobi,Eastern Africa,Africa,Kenyan,1.000000,38.000000,276300.0,...,54027487,23.42860,38358435,15669052,2.41,5.11,Hybrid regime,15.4,Uhuru Kenyatta,President
115,Morocco,Kingdom of Morocco,Moroccan dirham,Rabat,Northern Africa,Africa,Moroccan,32.000000,-5.000000,303820.0,...,37457971,24.05060,13261620,24196351,1.78,4.99,Hybrid regime,25.0,Mohammed VI,King
25,Burkina Faso,Burkina Faso,West African CFA franc,Ouagadougou,Western Africa,Africa,Burkinabe,13.000000,-2.000000,121430.0,...,22673762,16.90140,15446047,7227715,3.19,4.75,Hybrid regime,12.9,Roch Marc Christian Kaboré,President
149,Sierra Leone,Republic of Sierra Leone,Sierra Leonean leone,Freetown,Western Africa,Africa,Sierra Leonean,8.500000,-11.500000,39490.0,...,8605718,12.32880,4833746,3771972,2.58,4.66,Hybrid regime,15.1,Julius Maada Bio,President
125,Nigeria,Federal Republic of Nigeria,Nigerian naira,Abuja,Western Africa,Africa,Nigerian,10.000000,8.000000,694500.0,...,218541212,3.61111,101575770,116965442,2.14,4.44,Hybrid regime,13.2,Muhammadu Buhari,President
171,The Gambia,Republic of The Gambia,Gambian dalasi,Banjul,Western Africa,Africa,Gambian,13.466667,-16.566667,6050.0,...,2705992,8.62069,978162,1727830,2.49,4.31,Hybrid regime,13.1,Adama Barrow,President
39,Côte d'Ivoire,Republic of Côte d'Ivoire,West African CFA franc,Yamoussoukro,Western Africa,Africa,Ivorian,8.000000,-5.000000,212000.0,...,28160542,14.17320,13330919,14829623,2.65,4.15,Hybrid regime,13.8,Alassane Ouattara,President
116,Mozambique,Republic of Mozambique,New Mozambican metical,Maputo,Eastern Africa,Africa,Mozambican,-18.250000,35.000000,414138.0,...,32969518,42.40000,20379448,12590070,2.39,3.85,Authoritarian,13.0,Filipe Nyusi,President
107,Mauritania,Islamic Republic of Mauritania,Mauritanian ouguiya,Nouakchott,Western Africa,Africa,Mauritanian,20.000000,-12.000000,396610.0,...,4736139,20.26140,2040187,2695952,2.47,3.82,Authoritarian,13.8,Mohamed Ould Ghazouani,President
124,Niger,Republic of Niger,West African CFA franc,Niamey,Western Africa,Africa,Nigerien,16.000000,8.000000,465970.0,...,26207977,25.90360,21780401,4427576,2.67,3.76,Authoritarian,10.5,Mahamadou Issoufou,President
36,Comoros,Union of the Comoros,Comorian franc,Moroni,Eastern Africa,Africa,Comoran,-12.166667,44.250000,1310.0,...,836774,16.66670,586880,249894,2.80,3.71,Authoritarian,16.3,Azali Assoumani,President
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
61,Gabon,Gabonese Republic,Central African CFA franc,Libreville,Middle Africa,Africa,Gabonese,-1.000000,11.750000,22126.4,...,2388992,15.38460,221340,2167652,2.20,3.61,Authoritarian,17.7,Ali Bongo Ondimba,President
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
51,Egypt,Arab Republic of Egypt,Egyptian pound,Cairo,Northern Africa,Africa,Egyptian,27.000000,30.000000,39710.0,...,110990103,27.58040,63300985,47689118,1.38,3.36,Authoritarian,20.1,Abdel Fattah el-Sisi,President
57,Ethiopia,Federal Democratic Republic of Ethiopia,Ethiopian birr,Addis Ababa,Eastern Africa,Africa,Ethiopian,8.000000,38.000000,384761.0,...,123379924,41.48940,95420799,27959125,2.23,3.35,Authoritarian,14.7,Abiy Ahmed,Prime Minister
141,Rwanda,Republic of Rwanda,Rwandan franc,Kigali,Eastern Africa,Africa,Rwandan,-2.000000,30.000000,18117.0,...,13776698,61.25000,11335329,2441369,1.49,3.35,Authoritarian,15.2,Paul Kagame,President
37,Congo,Republic of Congo,Central African CFA franc,Brazzaville,Middle Africa,Africa,Congolese,-1.000000,15.000000,106280.0,...,5970424,14.56950,1866593,4103831,2.17,3.31,Authoritarian,14.3,Denis Sassou Nguesso,President
29,Cameroon,Republic of Cameroon,Central African CFA franc,Yaoundé,Middle Africa,Africa,Cameroonian,6.000000,12.000000,97500.0,...,27914536,33.88890,11519492,16395044,1.81,3.28,Authoritarian,13.6,Paul Biya,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President
68,Guinea,Republic of Guinea,Guinean franc,Conakry,Western Africa,Africa,Guinean,11.000000,-10.000000,145000.0,...,13859341,29.62960,8638804,5220537,2.34,3.14,Authoritarian,13.9,Alpha Condé,President
173,Togo,Republic of Togo,West African CFA franc,Lomé,Western Africa,Africa,Togolese,8.000000,1.166667,38200.0,...,8848699,18.68130,4962262,3886437,2.63,3.10,Authoritarian,14.8,Faure Gnassingbé,President
56,Eswatini,Kingdom of Eswatini,Swazi lilangeni,Lobamba,Southern Africa,Africa,Swazi,-26.500000,31.500000,12220.0,...,1201670,13.51350,906348,295322,1.59,3.03,Authoritarian,17.7,Mswati III,King
47,Djibouti,Republic of Djibouti,Djibouti franc,Djibouti,Eastern Africa,Africa,Djibouti,11.500000,43.000000,17020.0,...,1120849,26.15380,242328,878521,1.10,2.87,Authoritarian,20.0,Ismaïl Omar Guelleh,President
54,Eritrea,State of Eritrea,Eritrean nakfa,Asmara,Eastern Africa,Africa,Eritrean,15.000000,39.000000,75920.0,...,3684032,22.00000,2113713,1570319,0.97,2.37,Authoritarian,14.5,Isaias Afwerki,President
26,Burundi,Republic of Burundi,Burundi franc,Bujumbura,Eastern Africa,Africa,Burundian,-3.500000,30.000000,20330.0,...,12889576,38.21140,11031286,1858290,1.48,2.33,Authoritarian,11.9,Pierre Nkurunziza,President
96,Libya,Socialist People's Libyan Arab Jamahiriya,Libyan dinar,Tripoli,Northern Africa,Africa,Libyan,25.000000,17.000000,153500.0,...,6812341,16.47060,1273772,5538569,1.40,2.19,Authoritarian,22.6,Fayez al-Sarraj,Prime Minister
162,Sudan,Republic of the Sudan,Sudanese pound,Khartoum,Northern Africa,Africa,Sudanese,15.000000,30.000000,694058.0,...,46874204,30.51640,30020115,16854089,1.08,2.15,Authoritarian,14.5,Abdel Fattah al-Burhan,Leader of the Sovereignty Council
69,Guinea-Bissau,Republic of Guinea-Bissau,West African CFA franc,Bissau,Western Africa,Africa,Guinea-Bissauan,12.000000,-15.000000,8151.1,...,2105566,13.72550,1157198,948368,2.53,1.98,Authoritarian,14.5,Umaro Sissoco Embaló,President
53,Equatorial Guinea,Republic of Equatorial Guinea,Central African CFA franc,Malabo,Middle Africa,Africa,Equatorial Guinean,2.000000,10.000000,1885.2,...,1674908,31.00000,435309,1239599,1.34,1.92,Authoritarian,16.8,Teodoro Obiang Nguema Mbasogo,President
32,Chad,Republic of Chad,Central African CFA franc,N'Djamena,Middle Africa,Africa,Chadian,15.000000,19.000000,502380.0,...,17723315,25.88830,13458554,4264761,2.13,1.61,Authoritarian,11.2,Idriss Déby,President
31,Central African Republic,Central African Republic,Central African CFA franc,Bangui,Middle Africa,Africa,Central African,7.000000,21.000000,50800.0,...,5579144,12.85710,3173417,2405727,1.65,1.52,Authoritarian,10.8,Faustin-Archange Touadéra,President
45,Dem. Rep. Congo,Democratic Republic of the Congo,Congolese franc,Kinshasa,Middle Africa,Africa,Congolese,0.000000,25.000000,335720.0,...,99010212,12.80000,52636799,46373413,1.51,1.49,Authoritarian,11.7,Félix Tshisekedi,President
154,Somalia,Somali Democratic Republic,Somali shilling,Mogadishu,Eastern Africa,Africa,Somali,10.000000,49.000000,441250.0,...,17597511,19.70800,9269665,8327846,1.37,0.00,Unknown,11.3,Hassan Ali Khayre,Prime Minister
156,South Sudan,Republic of South Sudan,South Sudanese Pound,Juba,Middle Africa,Africa,South Sudanese,7.000000,30.000000,282510.0,...,10913164,32.36360,8638206,2274958,1.71,0.00,Unknown,12.5,Salva Kiir Mayardit,President
148,Seychelles,Republic of Seychelles,Seychelles rupee,Victoria,Eastern Africa,Africa,Seychellois,-4.583333,55.666667,15.5,...,100060,22.85710,41629,58431,2.66,0.00,Unknown,28.8,Danny Faure,President
144,São Tomé and Principe,Democratic Republic of São Tomé and Principe,São Tomé and Principe dobra,São Tomé,Middle Africa,Africa,Sao Tomean,1.000000,7.000000,440.0,...,227380,14.54550,55128,172252,0.00,0.00,Unknown,14.6,Evaristo Carvalho,President

In [168]:
# B. Isolating row items matching the maximum value inside the sub-dataframe
boolean_african_peak_pop_mask = df_african_continent_segment['population'] == df_african_continent_segment['population'].max()

# C. Extracting the final targeted row matrix and individual text attribute locations
peak_african_record = df_african_continent_segment[boolean_african_peak_pop_mask]
peak_african_country_name = df_african_continent_segment[boolean_african_peak_pop_mask]['country'].values[0]

print(f"Final Isolated Country Target Value: {peak_african_country_name}")

print("\nHighest Populated African Entity Row Summary View:")
peak_african_record

Final Isolated Country Target Value: Nigeria

Highest Populated African Entity Row Summary View:

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
125,Nigeria,Federal Republic of Nigeria,Nigerian naira,Abuja,Western Africa,Africa,Nigerian,10.0,8.0,694500.0,...,218541212,3.61111,101575770,116965442,2.14,4.44,Hybrid regime,13.2,Muhammadu Buhari,President